name: Noise Bot

on:
  schedule:
    - cron: "0 * * * *"   # cada hora (UTC)
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: noise-bot
  cancel-in-progress: false

jobs:
  run-noise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout con tu token (PAT)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}   # <- tu PAT fine-grained o classic
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar bot (commit + issue + PR + review + merge)
        env:
          # Usa tu PAT también para las llamadas a la API
          GITHUB_TOKEN:   ${{ secrets.ACTIONS_PAT }}

          # Identidad (usa tu email verificado o el noreply)
          GIT_USER_NAME:  "TuUsuario"
          GIT_USER_EMAIL: "TuUsuario@users.noreply.github.com"

          # (Opcional) pedir reviewers (usernames separados por coma)
          # REQUEST_REVIEWERS: "TuUsuario,OtroReviewer"

          # (Opcional) que el review sea APPROVE (si lo quitás, será comentario)
          APPROVE_PR: "1"
        run: |
          node -v
          node scripts/noise.js