name: Noise Bot

on:
  schedule:
    # Corre cada 30 minutos (UTC).
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: noise-bot
  cancel-in-progress: false

jobs:
  run-noise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ejecutar bot de ruido
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -v
          node scripts/noise.js